apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aaa-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: / # 访问这个路径会被跳转到svc-aaa服务
        pathType: Prefix
        backend:
          service:
            name: svc-aaa
            port:
              number: 7777
      